<?php

/**
 * @file
 * File Chooser Field Instagram plugin.
 * Author: Minnur Yunusov
 * mmyunusov@gmail.com
 */

/**
 * Implements hook_file_chooser_field_plugins().
 */
function file_chooser_field_instagram_file_chooser_field_plugins() {
  return array(
    'instagram' => array(
      'name' => t('Instagram'),
      'phpClassName' => 'InstagramPhotoPicker',
      'weight' => -6,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function file_chooser_field_instagram_menu() {

  $items['file-chooser-field-instagram/photos'] = array(
    'title' => 'My Instagram',
    'description' => 'My Instagram feed',
    'page callback' => 'file_chooser_field_instagram_photos',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Instagram gallery callback.
 */
function file_chooser_field_instagram_photos() {
  print theme('file_chooser_field_instagram_photos');
  drupal_exit();
}

/**
 * Implements hook_theme().
 */
function file_chooser_field_instagram_theme($existing, $type, $theme, $path) {
  return array(
    'file_chooser_field_instagram_photos' => array(
      'path' => $path . '/theme',
      'template' => 'file-chooser-field-instagram-photos',
      'variables' => array(),
      'preprocess functions' => array('file_chooser_field_instagram_preprocess_photos'),
      'file' => 'theme.inc',
    ),
  );
}
