<?php

/**
 * @file
 * Code for the Pages feature.
 */

include_once 'hr_pages.features.inc';

/**
 * Implements hook_og_features_registry().
 */
function hr_pages_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_pages';
  $feature->name = 'Pages';
  $feature->description = t('Provide static pages to your space.');
  $feature->components = array(
    'node' => array(
      'hr_page',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_page_alter().
 *
 * Hide the sidebar when "hide vertical menu" is checked.
 */
function hr_pages_page_alter(&$page) {
  $node = menu_get_object();
  if ($node && $node->type == 'hr_page' && isset($node->field_page_menu[LANGUAGE_NONE]) && $node->field_page_menu[LANGUAGE_NONE][0]['value'] == 1) {
    unset($page['sidebar_first']);
  }
}
