dist: bionic
language: php

php:
  - 7.4

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer self-update 2.5.5
  - composer install

script:
  - composer validate
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs vendor/drupal/coder/coder_sniffer
  - find -L $TRAVIS_BUILD_DIR/html/sites/all/modules/custom -name '*' -print0 | xargs -0 -n 1 -P 4 php -l
  - find -L $TRAVIS_BUILD_DIR/html/sites/all/modules/access -name '*' -print0 | xargs -0 -n 1 -P 4 php -l
  - find -L $TRAVIS_BUILD_DIR/html/sites/all/modules/ar -name '*' -print0 | xargs -0 -n 1 -P 4 php -l
  - find -L $TRAVIS_BUILD_DIR/html/sites/all/modules/ev -name '*' -print0 | xargs -0 -n 1 -P 4 php -l
  - find -L $TRAVIS_BUILD_DIR/html/sites/all/modules/hdx -name '*' -print0 | xargs -0 -n 1 -P 4 php -l
  - find -L $TRAVIS_BUILD_DIR/html/sites/all/modules/hid -name '*' -print0 | xargs -0 -n 1 -P 4 php -l
  - find -L $TRAVIS_BUILD_DIR/html/sites/all/modules/hr -name '*' -print0 | xargs -0 -n 1 -P 4 php -l
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs -np --report=full --standard=phpcs.xml $TRAVIS_BUILD_DIR/html/sites/all/modules/custom
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs -np --report=full --standard=phpcs.xml $TRAVIS_BUILD_DIR/html/sites/all/modules/access
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs -np --report=full --standard=phpcs.xml $TRAVIS_BUILD_DIR/html/sites/all/modules/ar
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs -np --report=full --standard=phpcs.xml $TRAVIS_BUILD_DIR/html/sites/all/modules/ev
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs -np --report=full --standard=phpcs.xml $TRAVIS_BUILD_DIR/html/sites/all/modules/hdx
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs -np --report=full --standard=phpcs.xml $TRAVIS_BUILD_DIR/html/sites/all/modules/hid
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs -np --report=full --standard=phpcs.xml $TRAVIS_BUILD_DIR/html/sites/all/modules/hr
