<?php
/**
 * @file
 * Primary hook implementations.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function hr_panels_cache_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager' || $module == 'panels' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_node_delete().
 */
function hr_panels_cache_node_delete($node) {
  hr_panels_cache_node_clear_cache($node);
}

/**
 * Implements hook_node_revision_delete().
 */
function hr_panels_cache_node_revision_delete($node) {
  hr_panels_cache_node_clear_cache($node);
}

/**
 * Implements hook_node_insert().
 */
function hr_panels_cache_node_insert($node) {
  hr_panels_cache_node_clear_cache($node);
}

/**
 * Implements hook_node_update().
 */
function hr_panels_cache_node_update($node) {
  hr_panels_cache_node_clear_cache($node);
}

/**
 * Implements hook_workbench_moderation_transition().
 */
function hr_panels_cache_workbench_moderation_transition($node, $previous_state, $new_state) {
  hr_panels_cache_node_clear_cache($node);
}

/**
 * This function is called from hook_node_*() and invalidates the panel cache
 * when a node is updated and it matches the criteria chosen in the caching of
 * any panels.
 *
 * @param $node
 *   The node object for the current node being saved.
 */
function hr_panels_cache_node_clear_cache($node) {
  // drupal_register_shutdown_function('_hr_panels_cache_node_clear_cache', $node);
  _hr_panels_cache_node_clear_cache($node);
}

function _hr_panels_cache_node_clear_cache($node) {
  // If the node is a group, clear the display of the group.
  if (og_is_group('node', $node)) {
    $cids = array('hr_panels_cache');
    $cids[] = 'gid_' . $node->nid;
    $cids[] = 'did_';
    _hr_panels_cache_node_clear_cache_by_cid($cids);
  }
  else {
    // Otherwise get the group from the current node.
    $groups = og_get_entity_groups('node', $node);
    if ($groups) {
      foreach (og_get_entity_groups('node', $node) as $entity_type => $og_memberships) {
        foreach ($og_memberships as $membership_id => $group_id) {
          // Clear node in all groups.
          $cids = array('hr_panels_cache');
          $cids[] = 'gid_' . $group_id;
          $cids[] = 'type_' . $node->type;
          $cids[] = 'nid_' . $node->nid;
          _hr_panels_cache_node_clear_cache_by_cid($cids);

          // Clear panes in all groups.
          $cids = array('hr_panels_cache');
          $cids[] = 'gid_' . $group_id;
          $cids[] = 'type_' . $node->type;
          $cids[] = 'did_';
          _hr_panels_cache_node_clear_cache_by_cid($cids);

          // Clear displays in all groups.
          $cids = array('hr_panels_cache');
          $cids[] = 'gid_' . $group_id;
          $cids[] = 'did_';
          _hr_panels_cache_node_clear_cache_by_cid($cids);
        }
      }
    }
  }
}

function _hr_panels_cache_node_clear_cache_by_cid($cids) {
  $cid = implode(':', $cids);
  cache_clear_all($cid, 'cache_panels', TRUE);
}
