<?php
/**
 * @file
 * Code for the Access Applications feature.
 */

include_once 'acc_applications.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function acc_applications_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'acc_applications';
  $feature->name = t('Access Applications');
  $feature->description = t('Humanitarian Access Applications Content Type, Views, Context, Search Index, Facets, Map');
  $feature->components = array(
    'node' => array(
      'acc_applications',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle($entity, $entity_id, $entity_type, $features)
 */
function acc_applications_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  if (isset($features['acc_applications'])) {
    $mlid = og_menu_single_get_link_mlid('node', $entity_id);
    if (empty($features['acc_applications'])) {
      menu_link_delete(NULL, 'node/'.$entity_id.'/access/applications');
    }
    else {
      // See if menu link already exists
      $menu_link = hr_core_menu_link_exists('node/'.$entity_id.'/access/applications', OG_MENU_SINGLE_MENU_NAME);
      if (empty($menu_link)) {
        $menu_link = array(
          'link_path' => 'node/'.$entity_id.'/access/applications',
          'link_title' => 'Access Applications',
          'menu_name' => OG_MENU_SINGLE_MENU_NAME,
          'weight' => 99,
          'plid' => $mlid,
        );
        menu_link_save($menu_link);
      }
    }
  }
}

