<?php
/**
 * @file
 * Code for the Access Applications feature.
 */

include_once 'acc_applications.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function acc_applications_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'acc_applications';
  $feature->name = 'Access Applications';
  $feature->description = t('Humanitarian Access Applications Content Type, Views, Context, Search Index, Facets, Map');
  $feature->components = array(
    'node' => array(
      'acc_applications',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

