<?php
/**
 * @file
 * Code for the Webforms feature.
 */

include_once 'hr_webforms.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_webforms_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_webforms';
  $feature->name = 'Webforms';
  $feature->description = t('Create webforms in your space.');
  $feature->components = array(
    'node' => array(
      'webform',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

