<?php
/**
 * @file
 * Code for the Discussions feature.
 */

include_once 'hr_discussions.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_discussions_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_discussions';
  $feature->name = t('Discussions');
  $feature->description = t('Provide a forum to your space (BETA).');
  $feature->components = array(
    'node' => array(
      'hr_discussion',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle($entity, $entity_id, $entity_type, $features)
 */
function hr_discussions_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  if (isset($features['hr_discussions'])) {
    $mlid = og_menu_single_get_link_mlid('node', $entity_id);
    if (empty($features['hr_discussions'])) {
      menu_link_delete(NULL, 'node/'.$entity_id.'/discussions');
    }
    else {
      // See if menu link already exists
      $menu_link = menu_link_get_preferred('node/'.$entity_id.'/discussions', OG_MENU_SINGLE_MENU_NAME);
      if (empty($menu_link)) {
        $menu_link = array(
          'link_path' => 'node/'.$entity_id.'/discussions',
          'link_title' => 'Discussions',
          'menu_name' => OG_MENU_SINGLE_MENU_NAME,
          'weight' => 18,
          'plid' => $mlid,
        );
        menu_link_save($menu_link);
      }
    }
  }

}
