<?php
/**
 * @file
 * Code for the Discussions feature.
 */

include_once 'hr_discussions.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_discussions_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_discussions';
  $feature->name = 'Discussions';
  $feature->description = t('Provide a forum to your space (BETA).');
  $feature->components = array(
    'node' => array(
      'hr_discussion',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

