<?php
/**
 * @file
 * Code for the Discussions feature.
 */

include_once 'hr_discussions.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_discussions_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_discussions';
  $feature->name = t('Discussions');
  $feature->description = t('Provide a forum to your space (BETA).');
  $feature->components = array(
    'node' => array(
      'hr_discussion',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle().
 */
function hr_discussions_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  $menus_to_create = array(
    'hr_discussions' => array(
      'title' => 'Discussions',
      'path' => 'node/' . $entity_id . '/discussions',
      'weight' => 18,
    )
  );
  _hr_layout_og_menu_single_helper('hr_discussions', $features, $entity_id, $menus_to_create);
}
