<?php

/**
 * @file
 * Provides an API to use the FTS API.
 */

/**
 *  FTS URL
 */
define('FTS_URL', 'https://ocha_hrinfo:edfgz345Hjk@api.hpc.tools/v1/public/');

/**
 * Returns API endpoint.
 */
function _fts_get_api_endpoint() {
  return variable_get('fts_api_endpoint', FTS_URL);
}

/**
 * Get all appeals for the current year.
 */
function fts_get_appeals($year = '') {
  if (empty($year)) {
    $year = date('Y');
  }

  $cache = cache_get('fts_appeals_cache' . $year, 'cache');
  if (!$cache) {
    $response = drupal_http_request(_fts_get_api_endpoint() . 'plan/year/' . $year);
    $data = json_decode($response->data);
    $appeals = array();
    if (isset($data->data)) {
      foreach ($data->data as $plan) {
        $appeal = (object) $plan;
        $appeal->title = $plan->name;
        $appeals[$plan->id] = $appeal;
      }
      cache_set('fts_appeals_cache' . $year, $appeals, 'cache', REQUEST_TIME + 24 * 60 * 60);
    }
  }
  else {
    $appeals = $cache->data;
  }

  return $appeals;
}

/**
 * Get appeal information by appeal ID
 */
function fts_get_appeal($id) {
  $appeal = NULL;
  if (empty($id)) {
    return $appeal;
  }

  $cache = cache_get('fts_appeal_by_id_cache' . $id, 'cache');
  if (!$cache) {
    $response = drupal_http_request(_fts_get_api_endpoint() . 'plan/id/' . $id);
    $data = json_decode($response->data);
    if (isset($data->data)) {
      $appeal = $data->data;
      $appeal->title = $appeal->name;
      cache_set('fts_appeal_by_id_cache' . $id, $appeal, 'cache', REQUEST_TIME + 24 * 60 * 60);
    }
  }
  else {
    $appeal = $cache->data;
  }

  return $appeal;
}

/**
 * Get general funding information
 */
function fts_get_funding($params) {
  $funding = array();

  $query = drupal_http_build_query($params);
  $cache = cache_get('fts_funding::' . md5($query), 'cache');
  if (!$cache) {
    $response = drupal_http_request(_fts_get_api_endpoint() . 'fts/flow?' . $query);
    $data = json_decode($response->data);
    if (isset($data->data)) {
      $funding = new stdClass();
      if (isset($data->data->report1)) {
        $report1 = $data->data->report1;
        $funding->current_requirements = $report1->fundingTotals->total;
        $funding->funding = $report1->pledgeTotals->total + $report1->fundingTotals->total;

        if (isset($data->data->report3)) {
          $report3 = $data->data->report3;
          if (isset($report3->fundingTotals->objects[0]->singleFundingObjects)) {
            foreach ($report3->fundingTotals->objects[0]->singleFundingObjects as $funding_object) {
              if (!isset($funding->data[$funding_object->name])) {
                $funding->data[$funding_object->name] = 0;
              }
              $funding->data[$funding_object->name] = $funding_object->totalFunding;
            }
          }

          if (isset($report3->pledgeTotals->objects[0]->singleFundingObjects)) {
            foreach ($report3->pledgeTotals->objects[0]->singleFundingObjects as $funding_object) {
              if (!isset($funding->data[$funding_object->name])) {
                $funding->data[$funding_object->name] = 0;
              }
              $funding->data[$funding_object->name] = $funding_object->totalFunding;
            }
          }
        }
      }
      else {
        $funding->current_requirements = $data->data->incoming->fundingTotal;
        $funding->funding = $data->data->incoming->pledgeTotal + $data->data->incoming->fundingTotal;
      }
      cache_set('fts_funding' . md5($query), $funding, 'cache', REQUEST_TIME + 24 * 60 * 60);
    }
    else{
      $funding = $cache->data;
    }
  }

  return $funding;
}

/**
 * Get global clusters.
 */
function fts_get_global_clusters() {
  $clusters = array();
  // curl https://ocha_hrinfo:edfgz345Hjk@api.hpc.tools/v1/public/global-cluster

  $cache = cache_get('fts_appeals_cache_global_clusters', 'cache');
  if (!$cache) {
    $response = drupal_http_request(_fts_get_api_endpoint() . 'global-cluster');
    $data = json_decode($response->data);
    if (isset($data->data)) {
      $clusters = $data->data;
      cache_set('fts_appeals_cache_global_clusters', $clusters, 'cache', REQUEST_TIME + 24 * 60 * 60);
    }
  }
  else {
    $clusters = $cache->data;
  }

  return $clusters;
}

/**
 * Get clusters information by appeal
 *
 * @todo: remove.
 */
function fts_get_clusters_by_appeal($id) {
  // curl https://ocha_hrinfo:edfgz345Hjk@api.hpc.tools/v1/public/global-cluster
  if (empty($id)) {
    return array();
  }
  $cache = cache_get('clusters_by_appeal'.$id, 'cache');
  if(!$cache){
    $url = FTS_URL . 'cluster/appeal/'.$id.'.xml';
    $xml = simplexml_load_file($url);
    $clusters = array();
    if (isset($xml->Cluster)) {
      foreach ($xml->Cluster as $cluster) {
        $clusters[] = json_decode(json_encode($cluster));
      }
      cache_set('clusters_by_appeal'.$id, $clusters, 'cache', REQUEST_TIME + 24*60*60);
    }
    return $clusters;
  }
  else{
    return $cache->data;
  }
}

/**
 * Get information for a specific cluster within a specific appeal
 *
 * @todo: remove.
 */
function fts_get_cluster_by_appeal($appeal, $cluster_name) {
  $clusters = fts_get_clusters_by_appeal($appeal);
  $cluster_found = NULL;
  foreach ($clusters as $cluster) {
    if ($cluster->name == $cluster_name) {
      $cluster_found = $cluster;
      break;
    }
  }
  return $cluster_found;
}
