version: "3.9"

services:
  mail:
    hostname: mail
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
    user: root
#  db:
#    extends:
#      file: ${HOME}/.docksal/stacks/services.yml
#      service: mysql
#    volumes:
#      - project_root:/var/www:ro,nocopy,cached  # Project root volume (read-only)
#      - db_data:/var/lib/mysql  # Database data volume
#    tmpfs:
#      - /var/lib/mysql:uid=999,gid=999
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    environment:
      - XXXSOLR_DEFAULT_CONFIG_SET=7.x-1.14
    hostname: solr
    image: docksal/solr:7.5
    user: solr
    labels:
      - io.docksal.virtual-host=solr.${VIRTUAL_HOST}
  redis:
    hostname: redis
    image: redis:3.2.11
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

# volumes:
#   db_data:
#     driver_opts:
#       type: tmpfs
#       device: tmpfs
#
