<?php

/**
 * @file
 * Code for the News feature.
 */

include_once 'hr_news.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_news_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_news';
  $feature->name = 'Blog';
  $feature->description = t('Provide a blog to your space.');
  $feature->components = array(
    'node' => array(
      'hr_news',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_search_api_views_query_alter()
 *
 * Makes the news view available for disasters.
 */
function hr_news_search_api_views_query_alter(&$view, &$query) {
  if ($view->name == 'hr_news') {
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (reset($condition) == 'og_group_ref') {
          $nid = $condition[1];
          if (is_numeric($nid)) {
            $node = node_load($nid);
            if ($node->type == 'hr_disaster') {
              $condition = array('field_disasters', $nid, '=');
            }
            // Clusters as spaces
            // See http://atrium.humanitarianresponse.info/humanitarian_response/node/4363
            elseif ($node->type == 'hr_bundle') {
              $condition = array('field_bundles', $nid, '=');
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hr_news_form_hr_news_node_form_alter(&$form, &$form_state) {
  _hr_core_fix_entity_reference_ajax_calls($form, $form_state);
  if (module_exists('hs_taxonomy')) {
    if (isset($form['field_locations']['und']['#config'])) {
      $form['field_locations']['und']['#config']['dropbox']['title'] = t('Current selections');
      $form['field_locations']['und']['#config']['animation_delay'] = 0;
      $form['field_locations']['und']['#config']['level_labels'] = array(
        'status' => 1,
        'labels' => array(
          0 => t('Country'),
          1 => t('Admin 1'),
          2 => t('Admin 2'),
          3 => t('Admin 3'),
        ),
      );
    }
  }
}
