<?php
/**
 * @file
 * Code for the Offices feature.
 */

include_once 'hr_offices.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_offices_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_offices';
  $feature->name = 'Offices';
  $feature->description = t('Provide offices to your space.');
  $feature->components = array(
    'node' => array(
      'hr_office',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle().
 */
function hr_offices_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  $menus_to_create = array(
    'hr_offices' => array(
      'title' => 'Offices',
      'path' => 'node/' . $entity_id . '/offices',
      'weight' => 14,
    )
  );
  _hr_layout_og_menu_single_helper('hr_offices', $features, $entity_id, $menus_to_create);
}

