<?php
/**
 * @file
 * Code for the Offices feature.
 */

include_once 'hr_offices.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_offices_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_offices';
  $feature->name = t('Offices');
  $feature->description = t('Provide offices to your space.');
  $feature->components = array(
    'node' => array(
      'hr_office',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle($entity, $entity_id, $entity_type, $features)
 */
function hr_offices_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  if (isset($features['hr_offices'])) {
    $mlid = og_menu_single_get_link_mlid('node', $entity_id);
    if (empty($features['hr_offices'])) {
      menu_link_delete(NULL, 'node/'.$entity_id.'/offices');
    }
    else {
      // See if menu link already exists
      $menu_link = menu_link_get_preferred('node/'.$entity_id.'/offices', OG_MENU_SINGLE_MENU_NAME);
      if (empty($menu_link)) {
        $menu_link = array(
          'link_path' => 'node/'.$entity_id.'/offices',
          'link_title' => 'Offices',
          'menu_name' => OG_MENU_SINGLE_MENU_NAME,
          'weight' => 14,
          'plid' => $mlid,
        );
        menu_link_save($menu_link);
      }
    }
  }
}

