<?php
/**
 * @file
 * Module for New Relic Insight integration.
 */

/**
 * Implements hook_page_alter().
 */
function panels_newrelic_insight_page_alter(&$page) {
  if (!extension_loaded('newrelic')) {
    return;
  }

  $name = NULL;
  // Lets get our current page if any.
  $panel_page = page_manager_get_current_page();

  $params = array();
  $entity = NULL;

  if (isset($panel_page['name'])) {
    // If it's a known view, lets setup the name and parameters.
    switch ($panel_page['name']) {
      case 'node_view':
        if (isset($panel_page['contexts']['argument_entity_id:node_1']->data)) {
          $entity = $panel_page['contexts']['argument_entity_id:node_1']->data;
          $name = 'page_manager_node_view_page/' . $entity->type;
          $params['node-id'] = $entity->nid;
          $params['node-type'] = $entity->type;
        }
        break;

      case 'term_view':
        if (isset($panel_page['contexts']['argument_term_1']->data)) {
          $entity = $panel_page['contexts']['argument_term_1']->data;
          $name = 'page_manager_term_view_page/' . $entity->vocabulary_machine_name;
          $params['term-id'] = $entity->tid;
          $params['vocabulary'] = $entity->vocabulary_machine_name;
        }
        break;

      default:
        // If it's a page_manager page use the panel name.
        if ($panel_page['task']['task type'] == 'page') {
          $name = 'page_manager_page_execute/' . $panel_page['name'];
        }
    }

    // Grab a variant if it exists.
    if (isset($name) && isset($panel_page['handler']->conf['title'])) {
      $variant = $panel_page['handler']->conf['title'];
      $variant = strtolower(str_replace(' ', '_', $variant));
      $name .= '/' . $variant;
      $params['variant'] = $variant;
    }
  }
  else {
    // So were not using panels, maybe were on a regular node view then?
    $menu_item = menu_get_item();

    switch ($menu_item['path']) {
      case 'node/%':
        $name = 'node_page_view';
        if (isset($menu_item['page_arguments'][0])) {
          $entity = $menu_item['page_arguments'][0];
          $name .= '/' . $entity->type;
          $params['node-id'] = $entity->nid;
          $params['node-type'] = $entity->type;
        }
        break;

      case 'taxonomy/term/%':
        $name = 'term_page_view';
        if (isset($menu_item['page_arguments'][0])) {
          $entity = $menu_item['page_arguments'][0];
          $name .= '/' . $entity->vocabulary_machine_name;
          $params['term-id'] = $entity->tid;
          $params['vocabulary'] = $entity->vocabulary_machine_name;
        }
        break;

      case 'user/%':
        if (isset($menu_item['page_arguments'][0])) {
          $entity = $menu_item['page_arguments'][0];
          $params['user-id'] = $entity->uid;
        }
        break;

    }
  }

  // Support for panelizer.
  if (isset($entity) && isset($entity->panelizer['page_manager']->name)) {
    $params['panelizer'] = $entity->panelizer['page_manager']->name;
  }

  foreach ($params as $key => $value) {
    newrelic_add_custom_parameter($key, $value);
  }

  if (isset($name)) {
    newrelic_name_transaction($name);
  }

}
