language: php

matrix:
  allow_failures:
    - php: hhvm

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction
 - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v --exclude-no-stmt
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  irc: "irc.appliedirc.com#applied"
