<?php

/**
 * @file
 * Code for the Offices feature.
 */

include_once 'hr_offices.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_offices_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_offices';
  $feature->name = 'Offices';
  $feature->description = t('Provide offices to your space.');
  $feature->components = array(
    'node' => array(
      'hr_office',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}
