<?php
/**
 * @file
 * Code for the Organizations feature.
 */

include_once 'hr_organizations.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function hr_organizations_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
}

function hr_organizations_query_hr_organizations_acronym_alter($query) {
  //$request = $query->alterMetaData['restful_data_provider']->getRequest()->getParsedInput();
  $request = isset($_REQUEST['q']) ? $_REQUEST['q'] : '';
  if (!empty($request)) {
    $query->join('field_data_field_acronym', 'field_data_field_acronym', 'taxonomy_term.tid = field_data_field_acronym.entity_id');
    $or = db_or();
    $prefix = '%' . db_like($request) . '%';
    $or->condition('name', array($prefix), 'LIKE');
    $or->condition('field_data_field_acronym.field_acronym_value', array($prefix), 'LIKE');
    debug($query->__toString());
  }
  /*$tid = 8; // country music genre tag
  $query->join('field_data_field_genres', 'field_data_field_genres', 'node.nid = field_data_field_genres.entity_id');
  $or = db_or();
  if (!empty($name)) {
      $prefix = '%'. db_like($request) . '%';
      $or->condition('title', array($prefix), 'LIKE');
  }
  if (!empty($tid)) {
      $or->condition('field_data_field_genres.field_genres_tid', array($tid), "=");
  }
  $query->condition($or);*/
}
