<?php

/**
 * @file
 * File Chooser Field module - Drupal 7 version.
 * Author: Minnur Yunusov
 * mmyunusov@gmail.com
 */

// Load field hooks.
module_load_include('inc', 'file_chooser_field', 'file_chooser_field.field');

/**
 * Implements hook_menu().
 */
function file_chooser_field_menu() {

  $items['admin/config/media/file-chooser-field'] = array(
    'title' => 'File Chooser Field',
    'description' => 'Configure File Chooser Field settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('file_chooser_field_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'file_chooser_field.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['redirectCallback/%'] = array(
    'title' => 'Redirect URL callback',
    'description' => 'Configure File Chooser Field settings',
    'access callback' => TRUE,
    'page callback' => 'file_chooser_field_redirect_callback',
    'page arguments' => array(1),
    'file' => 'file_chooser_field.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function file_chooser_field_permission() {
  module_load_include('inc', 'file_chooser_field');
  $permissions = array();
  $plugins = file_chooser_field_load_plugins();
  foreach ($plugins as $name => $plugin) {
    $permissions['upload files from ' . $name] = array(
      'title' => t('Allow to use @name', array('@name' => $plugin['name'])),
      'description' => t('Users will be able to upload files from @name.', array('@name' => $plugin['name'])),
    );
  }
  return $permissions;
}

/**
 * Implements hook_theme().
 */
function file_chooser_field_theme($existing, $type, $theme, $path) {
  return array(
    'file_chooser_field' => array(
      'path' => $path . '/theme',
      'template' => 'file-chooser-field',
      'variables' => array(
        'label'   => NULL,
        'class' => NULL,
        'attributes' => array(),
      ),
      'preprocess functions' => array('file_chooser_field_preprocess_file_chooser_field'),
      'file' => 'theme.inc',
    ),
  );
}

/**
 * Implements hook_file_chooser_field_plugins().
 */
function file_chooser_field_file_chooser_field_plugins() {
  return array(
    'dropbox' => array(
      'name' => t('Dropbox JavaScript Chooser API'),
      'phpClassName' => 'DropboxChooserAPI',
      'weight' => -10,
    ),
    'google_drive' => array(
      'name' => t('Google Picker API'),
      'phpClassName' => 'GooglePickerAPI',
      'weight' => -9,
    ),
    'box' => array(
      'name' => t('Box File Picker'),
      'phpClassName' => 'BoxPickerAPI',
      'weight' => -8,
    ),
    'one_drive' => array(
      'name' => t('OneDrive'),
      'phpClassName' => 'OneDriveAPI',
      'weight' => -7,
    ),
    'example' => array(
      'name' => t('Example'),
      'phpClassName' => 'Example',
      'weight' => 0,
    ),
  );
}
