<?php

/**
 * @file
 * Code for the Access Incident feature.
 */

include_once 'acc_incidents.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function acc_incidents_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'acc_incidents';
  $feature->name = 'Access Incidents';
  $feature->description = t('Humanitarian Access Incidents Content Type, Views, Context, Search Index, Facets, Map');
  $feature->components = array(
    'node' => array(
      'acc_incident',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_init()
 *
 * Raises the memory limit on the node/%/access/incidents page.
 *
 * @TODO: Fix this hack by improving access performance.
 */
function acc_incidents_init() {
  $path = current_path();
  if (strstr($path, 'access/incidents') !== FALSE) {
    ini_set('memory_limit', '512M');
  }
}
