<?php
/**
 * @file
 * Code for the Access Incident feature.
 */

include_once 'acc_incidents.features.inc';
/**
 * Implements hook_og_features_registry()
 */
function acc_incidents_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'acc_incidents';
  $feature->name = 'Access Incidents';
  $feature->description = t('Humanitarian Access Incidents Content Type, Views, Context, Search Index, Facets, Map');
  $feature->components = array(
    'node' => array(
      'acc_incident',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_init()
 * Raises the memory limit on the node/%/access/incidents page
 * TODO: fix this hack by improving access performance
 */
function acc_incidents_init() {
  $path = current_path();
  if (strstr($path, 'access/incidents') !== FALSE) {
    ini_set('memory_limit', '512M');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function acc_incidents_form_acc_incident_node_form_alter(&$form, &$form_state) {
  if (module_exists('hs_taxonomy')) {
    if (isset($form['field_locations']['und']['#config'])) {
      $form['field_locations']['und']['#config']['dropbox']['title'] = t('Current selections');
      $form['field_locations']['und']['#config']['animation_delay'] = 0;
      $form['field_locations']['und']['#config']['level_labels'] = array(
        'status' => 1,
        'labels' => array(
          0 => t('Country'),
          1 => t('Admin 1'),
          2 => t('Admin 2'),
          3 => t('Admin 3'),
        ),
      );
    }
  }

  // Show multiple empty ones for locations.
  if (!isset($form['#node']->nid)) {
    $items_count = 4;
    $field_name = 'field_locations';
    _hr_document_render_multiple_input_lines($field_name, $items_count, $form, $form_state);
  }
}
