name: Run Composer Update

on:
  schedule:
    - cron: '30 5 * * 4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update The Thing
      id: update-action
      uses: UN-OCHA/actions/composer-update@main
      with:
        github_access_token: ${{ secrets.PAT }}
        patch_branch: 'develop'
        patch_packages: 'drupal/*'
        patch_maintainers: ${{ vars.DRUPAL_MAINTAINERS }}
        slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack_channel_name: ${{ vars.SLACK_CHANNEL }}
