<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_module_implements_alter().
 * Allows menu_alter hook to be executed last
 */
function hr_translations_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    case 'menu_alter':
      // Move some of our hook implementations to the end of the list.
      $group = $implementations['hr_translations'];
      unset($implementations['hr_translations']);
      $implementations['hr_translations'] = $group;
      break;
  }
}

/**
 * Implements hook_menu_alter()
 * Forbids access to translate tab to users who don't have permission to edit the node
 */
function hr_translations_menu_alter(&$items) {
  if (isset($items['node/%node/translate'])) {
    $items['node/%node/translate']['access callback'] = 'node_access';
    $items['node/%node/translate']['access arguments'] = array(
      'update',
      1,
    );
  }
}
